#!/usr/bin/python
my_file = open("/var/www/wordpress/wp-config.php", "w")

my_file.write("<?php\n")
my_file.write("/**\n")
my_file.write(" * The base configuration for WordPress\n")
my_file.write(" *\n")
my_file.write(" * The wp-config.php creation script uses this file during the installation.\n")
my_file.write(" * You don't have to use the web site, you can copy this file to 'wp-config.php'\n")
my_file.write(" * and fill in the values.\n")
my_file.write(" *\n")
my_file.write(" * This file contains the following configurations:\n")
my_file.write(" *\n")
my_file.write(" * * Database settings\n")
my_file.write(" * * Secret keys\n")
my_file.write(" * * Database table prefix\n")
my_file.write(" * * ABSPATH\n")
my_file.write(" *\n")
my_file.write(" * @link https://wordpress.org/support/article/editing-wp-config-php/\n")
my_file.write(" *\n")
my_file.write(" * @package WordPress\n")
my_file.write(" */\n")
my_file.write("\n")
my_file.write("// ** Database settings - You can get this info from your web host ** //\n")
my_file.write("/** The name of the database for WordPress */\n")
my_file.write("define( 'DB_NAME', 'wordpress' );\n")
my_file.write("\n")
my_file.write("/** Database username */\n")
my_file.write("define( 'DB_USER', 'admin' );\n")
my_file.write("\n")
my_file.write("/** Database password */\n")
my_file.write("define( 'DB_PASSWORD', 'bloo1234' );\n")
my_file.write("\n")
my_file.write("/** Database hostname */\n")
my_file.write("define( 'DB_HOST', 'database-1.ccv0icnxd217.us-east-1.rds.amazonaws.com' );\n")
my_file.write("\n")
my_file.write("/** Database charset to use in creating database tables. */\n")
my_file.write("define( 'DB_CHARSET', 'utf8' );\n")
my_file.write("\n")
my_file.write("/** The database collate type. Don't change this if in doubt. */\n")
my_file.write("define( 'DB_COLLATE', '' );\n")
my_file.write("\n")
my_file.write("/**#@+\n")
my_file.write(" * Authentication unique keys and salts.\n")
my_file.write(" *\n")
my_file.write(" * Change these to different unique phrases! You can generate these using\n")
my_file.write(" * the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}.\n")
my_file.write(" *\n")
my_file.write(" * You can change these at any point in time to invalidate all existing cookies.\n")
my_file.write(" * This will force all users to have to log in again.\n")
my_file.write(" *\n")
my_file.write(" * @since 2.6.0\n")
my_file.write(" */\n")
my_file.write("define( 'AUTH_KEY','put your unique phrase here' );\n")
my_file.write("define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );\n")
my_file.write("define( 'LOGGED_IN_KEY',    'put your unique phrase here' );\n")
my_file.write("define( 'NONCE_KEY','put your unique phrase here' );\n")
my_file.write("define( 'AUTH_SALT','put your unique phrase here' );\n")
my_file.write("define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );\n")
my_file.write("define( 'LOGGED_IN_SALT',   'put your unique phrase here' );\n")
my_file.write("define( 'NONCE_SALT','put your unique phrase here' );\n")
my_file.write("\n")
my_file.write("/**#@-*/\n")
my_file.write("\n")
my_file.write("/**\n")
my_file.write(" * WordPress database table prefix.\n")
my_file.write(" *\n")
my_file.write(" * You can have multiple installations in one database if you give each\n")
my_file.write(" * a unique prefix. Only numbers, letters, and underscores please!\n")
my_file.write(" */\n")
my_file.write(" $table_prefix = 'wp_';\n")
my_file.write("\n")
my_file.write("/**\n")
my_file.write(" * For developers: WordPress debugging mode.\n")
my_file.write(" *\n")
my_file.write(" * Change this to true to enable the display of notices during development.\n")
my_file.write(" * It is strongly recommended that plugin and theme developers use WP_DEBUG\n")
my_file.write(" * in their development environments.\n")
my_file.write(" *\n")
my_file.write(" * For information on other constants that can be used for debugging,\n")
my_file.write(" * visit the documentation.\n")
my_file.write(" *\n")
my_file.write(" * @link https://wordpress.org/support/article/debugging-in-wordpress/\n")
my_file.write(" */\n")
my_file.write("define( 'WP_DEBUG', false );\n")
my_file.write("\n")
my_file.write("/* Add any custom values between this line and the 'stop editing' line. */\n")
my_file.write("\n")
my_file.write("/* That's all, stop editing! Happy publishing. */\n")
my_file.write("\n")
my_file.write("/** Absolute path to the WordPress directory. */\n")
my_file.write("if ( ! defined( 'ABSPATH' ) ) {\n")
my_file.write("define( 'ABSPATH', __DIR__ . '/' );\n")
my_file.write("}\n")
my_file.write("\n")
my_file.write("/** Sets up WordPress vars and included files. */\n")
my_file.write("require_once ABSPATH . 'wp-settings.php';")

my_file.close()