---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: wordpress.pkr.hcl

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # initialize packer
      - name: Init project
        run: packer init .
        
        
      # fix session
      - name: fix session
        run: export "OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES"

      
      # build artifact
      - name: Build Artifact
        run: packer build wordpress.pkr.hcl  
